name: CI-Eslint # Name of our workflow

on: [push] # Repository event that will trigger the workflow

jobs:
  build:

    runs-on: ubuntu-latest # Environment job will run in

    steps:
      - uses: actions/checkout@v1
      - name: Dependencies installation
        run: npm ci
      - name: Start eslint
        run: npm run lint
      - name: Start eslint controller
        run: npm run lintconroller